CREATE TABLE [bkp].[fact_tbl_medical_claim_history] (
    [medical_claim_skey]                 BIGINT          NOT NULL,
    [wh_member_id]                       BIGINT          NOT NULL,
    [member_skey]                        BIGINT          NOT NULL,
    [carrier_member_id]                  BIGINT          NOT NULL,
    [claim_id]                           BIGINT          NOT NULL,
    [claim_line_id]                      BIGINT          NOT NULL,
    [client_adjustment_sequence]         BIGINT          NOT NULL,
    [service_from_date]                  DATETIME        NOT NULL,
    [service_to_date]                    DATETIME        NOT NULL,
    [paid_date]                          DATETIME        NOT NULL,
    [admission_flag]                     VARCHAR (10)    NULL,
    [admission_date]                     DATETIME        NOT NULL,
    [discharge_date]                     DATETIME        NOT NULL,
    [admission_days]                     BIGINT          NULL,
    [drg]                                BIGINT          NULL,
    [icd_proc_code_1]                    VARCHAR (50)    NULL,
    [icd_proc_code_2]                    VARCHAR (50)    NULL,
    [icd_proc_code_3]                    VARCHAR (50)    NULL,
    [icd_proc_code_4]                    VARCHAR (50)    NULL,
    [icd_proc_code_5]                    VARCHAR (50)    NULL,
    [proc_code]                          VARCHAR (50)    NULL,
    [revenue_code]                       VARCHAR (50)    NULL,
    [service_type]                       TEXT            NULL,
    [bill_type_code]                     VARCHAR (50)    NULL,
    [network_ind]                        TEXT            NULL,
    [capitation]                         TEXT            NULL,
    [major_service_category]             TEXT            NULL,
    [minor_service_category]             TEXT            NULL,
    [minor_service_subcategory]          TEXT            NULL,
    [allowed_amount]                     DECIMAL (10, 5) NOT NULL,
    [paid_amount]                        DECIMAL (10, 5) NOT NULL,
    [coinsurance_amount]                 DECIMAL (10, 5) NOT NULL,
    [copay_amount]                       DECIMAL (10, 5) NOT NULL,
    [deductible_amount]                  DECIMAL (10, 5) NOT NULL,
    [cob_amount]                         DECIMAL (10, 5) NOT NULL,
    [claim_type]                         TEXT            NULL,
    [claim_status]                       TEXT            NULL,
    [refering_provider_id]               BIGINT          NULL,
    [servicing_provider_id]              BIGINT          NULL,
    [servicing_provider_type]            TEXT            NULL,
    [servicing_provider_speciality_code] VARCHAR (50)    NULL,
    [billing_provider_id]                BIGINT          NULL,
    [group_npi]                          TEXT            NULL,
    [place_of_service_code]              VARCHAR (50)    NULL,
    [speciality_code_description]        TEXT            NULL,
    [admit_source_code]                  VARCHAR (50)    NULL,
    [icd_version]                        VARCHAR (50)    NULL,
    [diagnosis_code_1]                   VARCHAR (50)    NULL,
    [diagnosis_code_2]                   VARCHAR (50)    NULL,
    [diagnosis_code_3]                   VARCHAR (50)    NULL,
    [diagnosis_code_4]                   VARCHAR (50)    NULL,
    [diagnosis_code_5]                   VARCHAR (50)    NULL,
    [diagnosis_code_6]                   VARCHAR (50)    NULL,
    [diagnosis_code_7]                   VARCHAR (50)    NULL,
    [diagnosis_code_8]                   VARCHAR (50)    NULL,
    [diagnosis_code_9]                   VARCHAR (50)    NULL,
    [diagnosis_code_10]                  VARCHAR (50)    NULL,
    [diagnosis_code_11]                  VARCHAR (50)    NULL,
    [diagnosis_code_12]                  VARCHAR (50)    NULL,
    [diagnosis_code_13]                  VARCHAR (50)    NULL,
    [diagnosis_code_14]                  VARCHAR (50)    NULL,
    [diagnosis_code_15]                  VARCHAR (50)    NULL,
    [diagnosis_code_16]                  VARCHAR (50)    NULL,
    [diagnosis_code_17]                  VARCHAR (50)    NULL,
    [diagnosis_code_18]                  VARCHAR (50)    NULL,
    [diagnosis_code_19]                  VARCHAR (50)    NULL,
    [diagnosis_code_20]                  VARCHAR (50)    NULL,
    [diagnosis_code_21]                  VARCHAR (50)    NULL,
    [diagnosis_code_22]                  VARCHAR (50)    NULL,
    [diagnosis_code_23]                  VARCHAR (50)    NULL,
    [diagnosis_code_24]                  VARCHAR (50)    NULL,
    [diagnosis_code_25]                  VARCHAR (50)    NULL,
    [provider_skey]                      BIGINT          NOT NULL,
    [run_instance_skey]                  BIGINT          NOT NULL,
    [source_file_skey]                   BIGINT          NOT NULL,
    [year]                               INT             NOT NULL,
    [month]                              INT             NOT NULL,
    [client_name]                        TEXT            NOT NULL,
    [carrier_name]                       TEXT            NOT NULL,
    [dw_inserted_timestamp]              DATETIME        NOT NULL,
    [dw_updated_timestamp]               DATETIME        NOT NULL
);

