CREATE TABLE [land].[tbl_eligibility_HCSC] (
    [Member Key]                     VARCHAR (MAX) NULL,
    [Account Number]                 VARCHAR (MAX) NULL,
    [Group Number]                   VARCHAR (MAX) NULL,
    [Section Number]                 VARCHAR (MAX) NULL,
    [Contract Type]                  VARCHAR (MAX) NULL,
    [Product Line]                   VARCHAR (MAX) NULL,
    [Product Type]                   VARCHAR (MAX) NULL,
    [Subscriber ID]                  VARCHAR (MAX) NULL,
    [Subscriber SSN]                 VARCHAR (MAX) NULL,
    [Member SSN]                     VARCHAR (MAX) NULL,
    [Member Number]                  VARCHAR (MAX) NULL,
    [Client Member ID]               VARCHAR (MAX) NULL,
    [Member DOB]                     VARCHAR (MAX) NULL,
    [Member Gender]                  VARCHAR (MAX) NULL,
    [Member Relationship Code]       VARCHAR (MAX) NULL,
    [Member Status]                  VARCHAR (MAX) NULL,
    [Member Medicare Status Code]    VARCHAR (MAX) NULL,
    [Member First Name]              VARCHAR (MAX) NULL,
    [Member Last Name]               VARCHAR (MAX) NULL,
    [Member Original Effective Date] VARCHAR (MAX) NULL,
    [Member Phone]                   VARCHAR (MAX) NULL,
    [Member Email]                   VARCHAR (MAX) NULL,
    [Subscriber Address]             VARCHAR (MAX) NULL,
    [Subscriber City]                VARCHAR (MAX) NULL,
    [Subscriber State]               VARCHAR (MAX) NULL,
    [Subscriber Zip]                 VARCHAR (MAX) NULL,
    [Member Effective Date]          VARCHAR (MAX) NULL,
    [Member Cancel Date]             VARCHAR (MAX) NULL,
    [Benefit Agreement]              VARCHAR (MAX) NULL,
    [Characteristic Code 1]          VARCHAR (MAX) NULL,
    [Characteristic Description 1]   VARCHAR (MAX) NULL,
    [Characteristic Code 2]          VARCHAR (MAX) NULL,
    [Characteristic Description 2]   VARCHAR (MAX) NULL,
    [Characteristic Code 3]          VARCHAR (MAX) NULL,
    [Characteristic Description 3]   VARCHAR (MAX) NULL,
    [Characteristic Code 4]          VARCHAR (MAX) NULL,
    [Characteristic Description 4]   VARCHAR (MAX) NULL,
    [Characteristic Code 5]          VARCHAR (MAX) NULL,
    [Characteristic Description 5]   VARCHAR (MAX) NULL,
    [Characteristic Code 6]          VARCHAR (MAX) NULL,
    [Characteristic Description 6]   VARCHAR (MAX) NULL,
    [Filler_1]                       VARCHAR (MAX) NULL,
    [Filler_2]                       VARCHAR (MAX) NULL,
    [Filler_3]                       VARCHAR (MAX) NULL,
    [Filler_4]                       VARCHAR (MAX) NULL,
    [Filler_5]                       VARCHAR (MAX) NULL
);

