CREATE TABLE [land].[tbl_eligibility] (
    [S.No.]                           INT           IDENTITY (1, 1) NOT NULL,
    [Member ID]                       VARCHAR (100) NULL,
    [Employee ID]                     VARCHAR (100) NULL,
    [First Name]                      VARCHAR (100) NULL,
    [Last Name]                       VARCHAR (100) NULL,
    [Relationship Code]               VARCHAR (100) NULL,
    [Member Date of Birth]            VARCHAR (100) NULL,
    [Member Gender]                   VARCHAR (100) NULL,
    [Plan ID]                         VARCHAR (100) NULL,
    [Member Status]                   VARCHAR (100) NULL,
    [Benefit Coverage Effective Date] VARCHAR (100) NULL,
    [Benefit Coverage End Date]       VARCHAR (100) NULL,
    [Reason for End]                  VARCHAR (100) NULL,
    [SSN]                             VARCHAR (100) NULL,
    [Pharmacy Indicator]              VARCHAR (100) NULL,
    [Home Phone]                      VARCHAR (100) NULL,
    [Cell Phone]                      VARCHAR (100) NULL,
    [Email]                           VARCHAR (100) NULL,
    [Address]                         VARCHAR (100) NULL,
    [City]                            VARCHAR (100) NULL,
    [State]                           VARCHAR (100) NULL,
    [Zip]                             VARCHAR (100) NULL,
    [PCP ID]                          VARCHAR (100) NULL,
    [Medicare Indicator]              VARCHAR (100) NULL,
    [Subscriber SSN]                  VARCHAR (100) NULL,
    [Member Middle Initial]           VARCHAR (100) NULL,
    [Account Number]                  VARCHAR (100) NULL,
    [Branch]                          VARCHAR (100) NULL,
    [Account Type]                    VARCHAR (100) NULL,
    [Account Subtype ]                VARCHAR (100) NULL,
    [Account Subtype 2]               VARCHAR (100) NULL,
    [Member Month Year Month]         VARCHAR (100) NULL,
    [Member Address Line 2]           VARCHAR (100) NULL,
    [Subscriber First Name]           VARCHAR (100) NULL,
    [Subscriber Middle Initial]       VARCHAR (100) NULL,
    [Subscriber Last Name]            VARCHAR (100) NULL,
    [Subscriber Birth Date]           VARCHAR (100) NULL,
    [Subscriber Sex]                  VARCHAR (100) NULL,
    [Subscriber Address]              VARCHAR (100) NULL,
    [Subscriber City]                 VARCHAR (100) NULL,
    [Subscriber State]                VARCHAR (100) NULL,
    [Subscriber Zip]                  VARCHAR (100) NULL,
    [Group Number]                    VARCHAR (100) NULL,
    [Section Number]                  VARCHAR (100) NULL,
    [Contract Type]                   VARCHAR (100) NULL,
    [Product Line]                    VARCHAR (100) NULL,
    [Product Type]                    VARCHAR (100) NULL,
    [Client Member ID]                VARCHAR (100) NULL,
    [Member Original Effective Date]  VARCHAR (100) NULL,
    [Benefit Agreement]               VARCHAR (100) NULL,
    [Characteristic Code 1]           VARCHAR (100) NULL,
    [Characteristic Description 1]    VARCHAR (100) NULL,
    [Characteristic Code 2]           VARCHAR (100) NULL,
    [Characteristic Description 2]    VARCHAR (100) NULL,
    [Characteristic Code 3]           VARCHAR (100) NULL,
    [Characteristic Description 3]    VARCHAR (100) NULL,
    [Characteristic Code 4]           VARCHAR (100) NULL,
    [Characteristic Description 4]    VARCHAR (100) NULL,
    [Characteristic Code 5]           VARCHAR (100) NULL,
    [Characteristic Description 5]    VARCHAR (100) NULL,
    [Characteristic Code 6]           VARCHAR (100) NULL,
    [Characteristic Description 6]    VARCHAR (100) NULL,
    [Date_Inserted]                   DATETIME      DEFAULT (getdate()) NULL,
    [Date_Updated]                    DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([S.No.] ASC)
);

