CREATE TABLE [land].[tbl_medical_claim_uhc] (
    [POLICY]             VARCHAR (200) NULL,
    [SUBSCRIBER NUMBER]  VARCHAR (200) NULL,
    [MEMBER ID]          VARCHAR (200) NULL,
    [CLAIM NUMBER]       VARCHAR (200) NULL,
    [FIRST SERVICE DATE] VARCHAR (200) NULL,
    [LAST SERVICE DATE]  VARCHAR (200) NULL,
    [PAID DATE]          VARCHAR (200) NULL,
    [CLAIM TYPE]         VARCHAR (200) NULL,
    [BILL TYPE]          VARCHAR (200) NULL,
    [PRIMARY DIAG]       VARCHAR (200) NULL,
    [SECOND DIAG]        VARCHAR (200) NULL,
    [TERTIARY DIAG]      VARCHAR (200) NULL,
    [PROCEDURE CODE]     VARCHAR (200) NULL,
    [PROCEDURE TYPE]     VARCHAR (200) NULL,
    [ICD10 PROC]         VARCHAR (200) NULL,
    [PAID AMOUNT]        VARCHAR (200) NULL
);

