CREATE TABLE [land].[tbl_medical_claim_BCBS_MN] (
    [EMPLOYEE IDENTIFICATION]                                   VARCHAR (MAX) NULL,
    [EMPLOYEE AGREEMENT NUMBER]                                 VARCHAR (MAX) NULL,
    [EMPLOYEE LAST NAME]                                        VARCHAR (MAX) NULL,
    [EMPLOYEE FIRST NAME]                                       VARCHAR (MAX) NULL,
    [EMPLOYEE DATE OF BIRTH]                                    VARCHAR (MAX) NULL,
    [EMPLOYEE GENDER]                                           VARCHAR (MAX) NULL,
    [EMPLOYEE ADDRESS LINE 1]                                   VARCHAR (MAX) NULL,
    [EMPLOYEE ADDRESS LINE 2]                                   VARCHAR (MAX) NULL,
    [EMPLOYEE ADDRESS CITY]                                     VARCHAR (MAX) NULL,
    [EMPLOYEE ADDRESS STATE]                                    VARCHAR (MAX) NULL,
    [EMPLOYEE ZIP CODE]                                         VARCHAR (MAX) NULL,
    [GROUP NUMBER]                                              VARCHAR (MAX) NULL,
    [PRODUCT]                                                   VARCHAR (MAX) NULL,
    [FILLER_1]                                                  VARCHAR (MAX) NULL,
    [SUBMITTING PLAN IDENTIFIER]                                VARCHAR (MAX) NULL,
    [CLAIM NUMBER]                                              VARCHAR (MAX) NULL,
    [SCCF NUMBER]                                               VARCHAR (MAX) NULL,
    [TYPE OF CLAIM IDENTIFIER]                                  VARCHAR (MAX) NULL,
    [FILLER_2]                                                  VARCHAR (MAX) NULL,
    [SOURCE FILE IDENTIFIER]                                    VARCHAR (MAX) NULL,
    [PATIENT LAST NAME]                                         VARCHAR (MAX) NULL,
    [PATIENT FIRST NAME]                                        VARCHAR (MAX) NULL,
    [PATIENT STATUS]                                            VARCHAR (MAX) NULL,
    [PATIENT DATE OF BIRTH]                                     VARCHAR (MAX) NULL,
    [PATIENT RELATIONSHIP CODE]                                 VARCHAR (MAX) NULL,
    [PATIENT GENDER CODE]                                       VARCHAR (MAX) NULL,
    [DATE CLAIM RECEIVED]                                       VARCHAR (MAX) NULL,
    [INCURRED DATE]                                             VARCHAR (MAX) NULL,
    [DISCHARGE DATE]                                            VARCHAR (MAX) NULL,
    [FINALIZATION DATE]                                         VARCHAR (MAX) NULL,
    [PROCESS STATUS CODE]                                       VARCHAR (MAX) NULL,
    [PLACE OF SERVICE]                                          VARCHAR (MAX) NULL,
    [LINE NUMBER]                                               VARCHAR (MAX) NULL,
    [TYPE OF SERVICE]                                           VARCHAR (MAX) NULL,
    [FILLER]                                                    VARCHAR (MAX) NULL,
    [ER INDICATOR]                                              VARCHAR (MAX) NULL,
    [FILLER_3]                                                  VARCHAR (MAX) NULL,
    [PRIMARY PROCEDURE CODE]                                    VARCHAR (MAX) NULL,
    [TYPE OF PROCEDURE CODE INDICATOR]                          VARCHAR (MAX) NULL,
    [PRIMARY PROCEDURE CODE MODIFIER]                           VARCHAR (MAX) NULL,
    [SECONDARY PROCDURE CODE MODIFIER]                          VARCHAR (MAX) NULL,
    [PROCEDURE CODE #2]                                         VARCHAR (MAX) NULL,
    [PROCEDURE CODE #3]                                         VARCHAR (MAX) NULL,
    [FILLER_4]                                                  VARCHAR (MAX) NULL,
    [CLASSIFICATION OF PROVIDER]                                VARCHAR (MAX) NULL,
    [BILLING PROVIDER IDENTIFIER]                               VARCHAR (MAX) NULL,
    [BILLING PROVIDER IDENTIFIER TYPE]                          VARCHAR (MAX) NULL,
    [BILLING NAME OF PHYSICIAN/PROVIDER]                        VARCHAR (MAX) NULL,
    [BILLING PROVIDER ADDRESS 1]                                VARCHAR (MAX) NULL,
    [BILLING PROVIDER ADDRESS 2]                                VARCHAR (MAX) NULL,
    [BILLING PROVIDER CITY]                                     VARCHAR (MAX) NULL,
    [BILLING PROVIDER STATE]                                    VARCHAR (MAX) NULL,
    [BILLING PROVIDER ZIP CODE]                                 VARCHAR (MAX) NULL,
    [BILLING PROVIDER SPECIALTY CODE]                           VARCHAR (MAX) NULL,
    [PAID IN or OUT OF NETWORK]                                 VARCHAR (MAX) NULL,
    [PRIMARY CARE PHYSICIAN IDENTIFIER]                         VARCHAR (MAX) NULL,
    [FILLER_5]                                                  VARCHAR (MAX) NULL,
    [PERFORMING PROVIDER IDENTIFIER]                            VARCHAR (MAX) NULL,
    [PERFORMING PROVIDER IDENTIFIER TYPE]                       VARCHAR (MAX) NULL,
    [MEDICAL RECORD NUMBER]                                     VARCHAR (MAX) NULL,
    [TYPE OF REIMBURSEMENT]                                     VARCHAR (MAX) NULL,
    [PAYMENT RECIPIENT CODE]                                    VARCHAR (MAX) NULL,
    [DRG CODE]                                                  VARCHAR (MAX) NULL,
    [TYPE OF ADMISSION INDICATOR]                               VARCHAR (MAX) NULL,
    [FILLER_6]                                                  VARCHAR (MAX) NULL,
    [PROVIDER ALLOW CHARGE]                                     VARCHAR (MAX) NULL,
    [FILLER_7]                                                  VARCHAR (MAX) NULL,
    [DEDUCTIBLE AMOUNT]                                         VARCHAR (MAX) NULL,
    [COINSURANCE AMOUNT]                                        VARCHAR (MAX) NULL,
    [COPAY AMOUNT]                                              VARCHAR (MAX) NULL,
    [AMOUNT EXCEEDING MAXIUM]                                   VARCHAR (MAX) NULL,
    [EMPLOYEE PENALTY]                                          VARCHAR (MAX) NULL,
    [OTHER EMPLOYEE LIABILITY]                                  VARCHAR (MAX) NULL,
    [FILLER_8]                                                  VARCHAR (MAX) NULL,
    [OTHER COB AMOUNT]                                          VARCHAR (MAX) NULL,
    [SALES TAX]                                                 VARCHAR (MAX) NULL,
    [SERVICE ADDITIONAL PAYMENT OR SURCHARGE AMOUNT]            VARCHAR (MAX) NULL,
    [PROVIDER APPROVED TO PAY AMOUNT]                           VARCHAR (MAX) NULL,
    [PER CLAIM ADMINISTRATION / ACCESS FEE]                     VARCHAR (MAX) NULL,
    [FILLER_9]                                                  VARCHAR (MAX) NULL,
    [WAREHOUSE LOAD DATE]                                       VARCHAR (MAX) NULL,
    [FILLER_10]                                                 VARCHAR (MAX) NULL,
    [NATIONAL DRUG CODE]                                        VARCHAR (MAX) NULL,
    [DISPENSE AS WRITTEN CODE]                                  VARCHAR (MAX) NULL,
    [DRUG FORMULARY INDICATOR]                                  VARCHAR (MAX) NULL,
    [DRUG MAINTENANCE INDICATOR]                                VARCHAR (MAX) NULL,
    [DRUG PRODUCT NAME]                                         VARCHAR (MAX) NULL,
    [DATE PRESCRIPTION WRITTEN]                                 VARCHAR (MAX) NULL,
    [FILLER_11]                                                 VARCHAR (MAX) NULL,
    [PHARMACY PROVIDER FEE CLASS CODE]                          VARCHAR (MAX) NULL,
    [FILLER_12]                                                 VARCHAR (MAX) NULL,
    [DRUG QUANTITY DISPENSED AMOUNT]                            VARCHAR (MAX) NULL,
    [PRESCRIBED DAYS SUPPLIED]                                  VARCHAR (MAX) NULL,
    [DRUG DISPENSING FEE AMOUNT]                                VARCHAR (MAX) NULL,
    [PRESCRIPTION REFILL NUMBER]                                VARCHAR (MAX) NULL,
    [AVERAGE WHOLESALE UNIT PRICE]                              VARCHAR (MAX) NULL,
    [FILLER_13]                                                 VARCHAR (MAX) NULL,
    [CLAIM DRUG COMPOUND CODE]                                  VARCHAR (MAX) NULL,
    [FILLER_14]                                                 VARCHAR (MAX) NULL,
    [INGREDIENT COST PAID]                                      VARCHAR (MAX) NULL,
    [DRUG STRENGTH MEASUREMENT]                                 VARCHAR (MAX) NULL,
    [DRUG UNIT MEASURE CODE]                                    VARCHAR (MAX) NULL,
    [DRUG PRESCRIPTION IDENTIFIER]                              VARCHAR (MAX) NULL,
    [DRUG PRIOR AUTHORIZATION NUMBER]                           VARCHAR (MAX) NULL,
    [REVENUE CODE]                                              VARCHAR (MAX) NULL,
    [FILLER_15]                                                 VARCHAR (MAX) NULL,
    [CLIENT NUMBER]                                             VARCHAR (MAX) NULL,
    [NUMBER OF UNITS]                                           VARCHAR (MAX) NULL,
    [NATIONAL PROVIDER IDENTIFIER - BILLING PROVIDER]           VARCHAR (MAX) NULL,
    [NATIONAL PROVIDER IDENTIFIER - PERFORMING PROVIDER]        VARCHAR (MAX) NULL,
    [FILLER_16]                                                 VARCHAR (MAX) NULL,
    [PRIMARY DIAGNOSIS CODE]                                    VARCHAR (MAX) NULL,
    [SECONDARY DIAGNOSIS (2)]                                   VARCHAR (MAX) NULL,
    [SECONDARY DIAGNOSIS (3)]                                   VARCHAR (MAX) NULL,
    [SECONDARY DIAGNOSIS (4)]                                   VARCHAR (MAX) NULL,
    [TYPE OF DIAGNOSIS CODE INDICATOR]                          VARCHAR (MAX) NULL,
    [FACILITY TYPE OF BILL]                                     VARCHAR (MAX) NULL,
    [NATIONAL ORDERING PROVIDER - PHARMACY CLAIMS]              VARCHAR (MAX) NULL,
    [FILLER_17]                                                 VARCHAR (MAX) NULL,
    [CLAIM LINE SERVICE END DATE]                               VARCHAR (MAX) NULL,
    [FILLER_18]                                                 VARCHAR (MAX) NULL,
    [Used for Internal Use]                                     VARCHAR (MAX) NULL,
    [CLAIM DRUG BRAND GENERIC CODE]                             VARCHAR (MAX) NULL,
    [DEPARTMENT CODE]                                           VARCHAR (MAX) NULL,
    [EMPLOYEE LOCATION CODE]                                    VARCHAR (MAX) NULL,
    [FILLER_19]                                                 VARCHAR (MAX) NULL,
    [CLAIM OTHER PARTY LIABILITY INSURANCE RESPONSIBILITY CODE] VARCHAR (MAX) NULL,
    [COVERAGE CATEGORY CODE]                                    VARCHAR (MAX) NULL,
    [CLIENT ASSIGN ID]                                          VARCHAR (MAX) NULL,
    [FILLER_20]                                                 VARCHAR (MAX) NULL
);

