CREATE TABLE [land].[tbl_medical_claim_truven] (
    [Member ID]                VARCHAR (200) NULL,
    [Claim Number]             VARCHAR (200) NULL,
    [Claim Detail Line Number] VARCHAR (200) NULL,
    [Claim Service Begin Date] VARCHAR (200) NULL,
    [Claim Service End Date]   VARCHAR (200) NULL,
    [Procedure Code 1]         VARCHAR (200) NULL,
    [Procedure Code 1 Type]    VARCHAR (200) NULL,
    [Procedure Code 2]         VARCHAR (200) NULL,
    [Procedure Code 2 Type]    VARCHAR (200) NULL,
    [Procedure Code 3]         VARCHAR (200) NULL,
    [Procedure Code 3 Type]    VARCHAR (200) NULL,
    [Procedure Code 4]         VARCHAR (200) NULL,
    [Procedure Code 4 Type]    VARCHAR (200) NULL,
    [Procedure Code 5]         VARCHAR (200) NULL,
    [Procedure Code 5 Type]    VARCHAR (200) NULL,
    [Paid Date]                VARCHAR (200) NULL,
    [Paid Amount]              VARCHAR (200) NULL,
    [Allowed Amount]           VARCHAR (200) NULL,
    [Coinsurance]              VARCHAR (200) NULL,
    [Copay]                    VARCHAR (200) NULL,
    [Claim Type]               VARCHAR (200) NULL,
    [COB Amout]                VARCHAR (200) NULL,
    [Bill Type]                VARCHAR (200) NULL,
    [Revenue Code]             VARCHAR (200) NULL,
    [Claim Status]             VARCHAR (200) NULL,
    [Type of Admission]        VARCHAR (200) NULL,
    [Diagnosis Code One]       VARCHAR (200) NULL,
    [Diagnosis Code Two]       VARCHAR (200) NULL,
    [Diagnosis Code Three]     VARCHAR (200) NULL,
    [Diagnosis Code Four]      VARCHAR (200) NULL,
    [Diagnosis Code Five]      VARCHAR (200) NULL,
    [Diagnosis Code Six]       VARCHAR (200) NULL,
    [Diagnosis Code Seven]     VARCHAR (200) NULL,
    [Diagnosis Code Eight]     VARCHAR (200) NULL,
    [Diagnosis Code Nine]      VARCHAR (200) NULL,
    [Diagnosis Code Ten]       VARCHAR (200) NULL,
    [Diagnosis Code Eleven]    VARCHAR (200) NULL,
    [Diagnosis Code Twelve]    VARCHAR (200) NULL,
    [Diagnosis Code Thirteen]  VARCHAR (200) NULL,
    [Diagnosis Code Fourteen]  VARCHAR (200) NULL,
    [Diagnosis Code Fifteen]   VARCHAR (200) NULL,
    [Diagnosis Code Sixteen]   VARCHAR (200) NULL,
    [Diagnosis Code Seventeen] VARCHAR (200) NULL,
    [Diagnosis Code Eighteen]  VARCHAR (200) NULL,
    [Diagnosis Code Nineteen]  VARCHAR (200) NULL,
    [Diagnosis Code Twenty]    VARCHAR (200) NULL
);

