
CREATE PROCEDURE  [dbo].[land_to_stg_table_eligibility]
@Carrier varchar(100),
@Client varchar(100),
@year int,
@month int,
@run_instance_skey int,
@source_file_skey int
AS
BEGIN
	
INSERT into [stg].[tbl_eligibility](
[Member ID],
[Employee ID],
[First Name],
[Last Name],
[Relationship Code],
[Member Date of Birth],
[Member Gender],
[Plan ID],
[Member Status],
[Benefit Coverage Effective Date],
[Benefit Coverage End Date],
[Reason for End],
[SSN],
[Pharmacy Indicator],
[Home Phone],
[Cell Phone],
[Email],
[Address],
[City],
[State],
[Zip],
[PCP ID],
[Medicare Indicator],
[Subscriber SSN],
[Member Middle Initial],
[Account Number],
[Branch],
[Account Type],
[Account Subtype ],
[Account Subtype 2],
[Member Month Year Month],
[Member Address Line 2],
[Subscriber First Name],
[Subscriber Middle Initial],
[Subscriber Last Name],
[Subscriber Birth Date],
[Subscriber Sex],
[Subscriber Address],
[Subscriber City],
[Subscriber State],
[Subscriber Zip],
[Group Number],
[Section Number],
[Contract Type],
[Product Line],
[Product Type],
[Client Member ID],
[Member Original Effective Date],
[Benefit Agreement],
[Characteristic Code 1],
[Characteristic Description 1],
[Characteristic Code 2],
[Characteristic Description 2],
[Characteristic Code 3],
[Characteristic Description 3],
[Characteristic Code 4],
[Characteristic Description 4],
[Characteristic Code 5],
[Characteristic Description 5],
[Characteristic Code 6],
[Characteristic Description 6],
[Carrier],[Client],[run_instance_skey],[source_file_skey],[Month],[Year]
)
select 
[Member ID],
Case When IsNumeric([Employee ID]) <> 0 THEN CONVERT(bigint,[Employee ID]) ELSE NULL end as [Employee ID],
[First Name],
[Last Name],
[Relationship Code],
CAST([Member Date of Birth] as date ),
[Member Gender],
[Plan ID],
[Member Status],
CAST([Benefit Coverage Effective Date] as date ),
CAST([Benefit Coverage End Date] as date ),
[Reason for End],
Case When IsNumeric([SSN]) <> 0 THEN CONVERT(bigint,[SSN]) ELSE NULL end as [SSN],
[Pharmacy Indicator],
[Home Phone],
[Cell Phone],
[Email],
[Address],
[City],
[State],
[Zip],
[PCP ID],
[Medicare Indicator],
Case When IsNumeric([Subscriber SSN]) <> 0 THEN CONVERT(bigint,[Subscriber SSN]) ELSE NULL end as [Subscriber SSN],
[Member Middle Initial],
Case When IsNumeric([Account Number]) <> 0 THEN CONVERT(bigint,[Account Number]) ELSE NULL end as [Account Number],
[Branch],
[Account Type],
[Account Subtype ],
[Account Subtype 2],
[Member Month Year Month],
[Member Address Line 2],
[Subscriber First Name],
[Subscriber Middle Initial],
[Subscriber Last Name],
[Subscriber Birth Date],
[Subscriber Sex],
[Subscriber Address],
[Subscriber City],
[Subscriber State],
Case When IsNumeric([Subscriber Zip]) <> 0 THEN CONVERT(bigint,[Subscriber Zip]) ELSE NULL end as [Subscriber Zip],
Case When IsNumeric([Group Number] + '.0e0') <> 0 THEN CAST([Group Number] as bigint) ELSE NULL end as [Group Number],
Case When IsNumeric([Section Number]) <> 0 THEN CONVERT(bigint,[Section Number]) ELSE NULL end as [Section Number],
[Contract Type],
[Product Line],
[Product Type],
[Client Member ID],
CAST([Member Original Effective Date] as date ),
[Benefit Agreement],
[Characteristic Code 1],
[Characteristic Description 1],
[Characteristic Code 2],
[Characteristic Description 2],
[Characteristic Code 3],
[Characteristic Description 3],
[Characteristic Code 4],
[Characteristic Description 4],
[Characteristic Code 5],
[Characteristic Description 5],
[Characteristic Code 6],
[Characteristic Description 6]
,@Carrier,@Client,@run_instance_skey,@source_file_skey,@month,@year
FROM land.tbl_eligibility

TRUNCATE table land.tbl_eligibility

END

