CREATE TABLE [dbo].[DATABASECHANGELOGLOCK] (
    [ID]          INT            NOT NULL,
    [LOCKED]      BIT            NOT NULL,
    [LOCKGRANTED] DATETIME2 (3)  NULL,
    [LOCKEDBY]    NVARCHAR (255) NULL,
    CONSTRAINT [PK_DATABASECHANGELOGLOCK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

