CREATE TABLE [dbo].[DATABASECHANGELOG] (
    [ID]            NVARCHAR (255) NOT NULL,
    [AUTHOR]        NVARCHAR (255) NOT NULL,
    [FILENAME]      NVARCHAR (255) NOT NULL,
    [DATEEXECUTED]  DATETIME2 (3)  NOT NULL,
    [ORDEREXECUTED] INT            NOT NULL,
    [EXECTYPE]      NVARCHAR (10)  NOT NULL,
    [MD5SUM]        NVARCHAR (35)  NULL,
    [DESCRIPTION]   NVARCHAR (255) NULL,
    [COMMENTS]      NVARCHAR (255) NULL,
    [TAG]           NVARCHAR (255) NULL,
    [LIQUIBASE]     NVARCHAR (20)  NULL,
    [CONTEXTS]      NVARCHAR (255) NULL,
    [LABELS]        NVARCHAR (255) NULL,
    [DEPLOYMENT_ID] NVARCHAR (10)  NULL
);

