CREATE TABLE [dbo].[SCHEDULER_JOB_DETAILS] (
    [SCHED_NAME]        VARCHAR (120) NOT NULL,
    [JOB_NAME]          VARCHAR (200) NOT NULL,
    [JOB_GROUP]         VARCHAR (200) NOT NULL,
    [DESCRIPTION]       VARCHAR (250) NULL,
    [JOB_CLASS_NAME]    VARCHAR (250) NOT NULL,
    [IS_DURABLE]        VARCHAR (1)   NOT NULL,
    [IS_NONCONCURRENT]  VARCHAR (1)   NOT NULL,
    [IS_UPDATE_DATA]    VARCHAR (1)   NOT NULL,
    [REQUESTS_RECOVERY] VARCHAR (1)   NOT NULL,
    [JOB_DATA]          IMAGE         NULL,
    CONSTRAINT [SCHEDULER_PK_JOB_DETAILS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [JOB_NAME] ASC, [JOB_GROUP] ASC)
);

