CREATE TABLE [dbo].[SCHEDULER_FIRED_TRIGGERS] (
    [SCHED_NAME]        VARCHAR (120) NOT NULL,
    [ENTRY_ID]          VARCHAR (95)  NOT NULL,
    [TRIGGER_NAME]      VARCHAR (200) NOT NULL,
    [TRIGGER_GROUP]     VARCHAR (200) NOT NULL,
    [INSTANCE_NAME]     VARCHAR (200) NOT NULL,
    [FIRED_TIME]        BIGINT        NOT NULL,
    [SCHED_TIME]        BIGINT        NOT NULL,
    [PRIORITY]          INT           NOT NULL,
    [STATE]             VARCHAR (16)  NOT NULL,
    [JOB_NAME]          VARCHAR (200) NULL,
    [JOB_GROUP]         VARCHAR (200) NULL,
    [IS_NONCONCURRENT]  VARCHAR (1)   NULL,
    [REQUESTS_RECOVERY] VARCHAR (1)   NULL,
    CONSTRAINT [SCHEDULER_PK_FIRED_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [ENTRY_ID] ASC)
);

