CREATE TABLE [dbo].[SCHEDULER_CRON_TRIGGERS] (
    [SCHED_NAME]      VARCHAR (120) NOT NULL,
    [TRIGGER_NAME]    VARCHAR (200) NOT NULL,
    [TRIGGER_GROUP]   VARCHAR (200) NOT NULL,
    [CRON_EXPRESSION] VARCHAR (120) NOT NULL,
    [TIME_ZONE_ID]    VARCHAR (80)  NULL,
    CONSTRAINT [SCHEDULER_PK_CRON_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC),
    CONSTRAINT [SCHEDULER_FK_CRON_TRIGGERS_TRIGGERS] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) REFERENCES [dbo].[SCHEDULER_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON DELETE CASCADE
);

