CREATE TABLE [dbo].[SCHEDULER_SIMPLE_TRIGGERS] (
    [SCHED_NAME]      VARCHAR (120) NOT NULL,
    [TRIGGER_NAME]    VARCHAR (200) NOT NULL,
    [TRIGGER_GROUP]   VARCHAR (200) NOT NULL,
    [REPEAT_COUNT]    BIGINT        NOT NULL,
    [REPEAT_INTERVAL] BIGINT        NOT NULL,
    [TIMES_TRIGGERED] BIGINT        NOT NULL,
    CONSTRAINT [SCHEDULER_PK_SIMPLE_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC),
    CONSTRAINT [SCHEDULER_FK_SIMPLE_TRIGGERS_TRIGGERS] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) REFERENCES [dbo].[SCHEDULER_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON DELETE CASCADE
);

