CREATE TABLE [dbo].[SCHEDULER_LOCKS] (
    [SCHED_NAME] VARCHAR (120) NOT NULL,
    [LOCK_NAME]  VARCHAR (40)  NOT NULL,
    CONSTRAINT [SCHEDULER_PK_LOCKS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [LOCK_NAME] ASC)
);

