CREATE TABLE [dbo].[SCHEDULER_CALENDARS] (
    [SCHED_NAME]    VARCHAR (120) NOT NULL,
    [CALENDAR_NAME] VARCHAR (200) NOT NULL,
    [CALENDAR]      IMAGE         NOT NULL,
    CONSTRAINT [SCHEDULER_PK_CALENDARS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [CALENDAR_NAME] ASC)
);

