CREATE TABLE [dbo].[SCHEDULER_BLOB_TRIGGERS] (
    [SCHED_NAME]    VARCHAR (120) NOT NULL,
    [TRIGGER_NAME]  VARCHAR (200) NOT NULL,
    [TRIGGER_GROUP] VARCHAR (200) NOT NULL,
    [BLOB_DATA]     IMAGE         NULL,
    CONSTRAINT [SCHEDULER_FK_BLOB_TRIGGERS_TRIGGERS] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) REFERENCES [dbo].[SCHEDULER_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON DELETE CASCADE
);

