CREATE TABLE [dbo].[SCHEDULER_PAUSED_TRIGGER_GRPS] (
    [SCHED_NAME]    VARCHAR (120) NOT NULL,
    [TRIGGER_GROUP] VARCHAR (200) NOT NULL,
    CONSTRAINT [SCHEDULER_PK_PAUSED_TRIGGER_GRPS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_GROUP] ASC)
);

