CREATE TABLE [dbo].[SCHEDULER_TRIGGERS] (
    [SCHED_NAME]     VARCHAR (120) NOT NULL,
    [TRIGGER_NAME]   VARCHAR (200) NOT NULL,
    [TRIGGER_GROUP]  VARCHAR (200) NOT NULL,
    [JOB_NAME]       VARCHAR (200) NOT NULL,
    [JOB_GROUP]      VARCHAR (200) NOT NULL,
    [DESCRIPTION]    VARCHAR (250) NULL,
    [NEXT_FIRE_TIME] BIGINT        NULL,
    [PREV_FIRE_TIME] BIGINT        NULL,
    [PRIORITY]       INT           NULL,
    [TRIGGER_STATE]  VARCHAR (16)  NOT NULL,
    [TRIGGER_TYPE]   VARCHAR (8)   NOT NULL,
    [START_TIME]     BIGINT        NOT NULL,
    [END_TIME]       BIGINT        NULL,
    [CALENDAR_NAME]  VARCHAR (200) NULL,
    [MISFIRE_INSTR]  SMALLINT      NULL,
    [JOB_DATA]       IMAGE         NULL,
    CONSTRAINT [SCHEDULER_PK_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC),
    CONSTRAINT [SCHEDULER_FK_TRIGGERS_JOB_DETAILS] FOREIGN KEY ([SCHED_NAME], [JOB_NAME], [JOB_GROUP]) REFERENCES [dbo].[SCHEDULER_JOB_DETAILS] ([SCHED_NAME], [JOB_NAME], [JOB_GROUP])
);

