CREATE TABLE [stg].[Arch_tbl_medical_claim] (
    [S.No.]                                                INT             IDENTITY (1, 1) NOT NULL,
    [Account_Number]                                       BIGINT          NULL,
    [Carrier_Member_ID]                                    VARCHAR (100)   NULL,
    [Claim_ID]                                             VARCHAR (100)   NULL,
    [Claim_Line_ID]                                        BIGINT          NULL,
    [Service_From_date]                                    DATE            NULL,
    [Servce_To_date]                                       DATE            NULL,
    [admission_date]                                       DATE            NULL,
    [discharge_date]                                       DATE            NULL,
    [Admission_ID]                                         VARCHAR (100)   NULL,
    [Type_of_Admission]                                    VARCHAR (100)   NULL,
    [Admitting_Diagnosis_Code]                             VARCHAR (100)   NULL,
    [Admit_source_code]                                    VARCHAR (100)   NULL,
    [Discharge_Status_Code]                                VARCHAR (100)   NULL,
    [Place of Service Code]                                BIGINT          NULL,
    [service Type]                                         BIGINT          NULL,
    [Line_Of_Business]                                     VARCHAR (100)   NULL,
    [PROC_CODE]                                            VARCHAR (100)   NULL,
    [PROC_CODE_2]                                          VARCHAR (100)   NULL,
    [PROC_CODE_TYPE]                                       VARCHAR (100)   NULL,
    [PROC_CODE_2_TYPE]                                     VARCHAR (100)   NULL,
    [Procedure_Code_Modifier]                              VARCHAR (100)   NULL,
    [ICD_Proc_code_1]                                      VARCHAR (100)   NULL,
    [ICD_Proc_code_2]                                      VARCHAR (100)   NULL,
    [ICD_Proc_code_3]                                      VARCHAR (100)   NULL,
    [ICD_Proc_code_4]                                      VARCHAR (100)   NULL,
    [ICD_Proc_code_5]                                      VARCHAR (100)   NULL,
    [Paid_date]                                            DATE            NULL,
    [Paid_amount]                                          DECIMAL (10, 2) NULL,
    [Allowed_amount]                                       DECIMAL (10, 2) NULL,
    [Deductible]                                           DECIMAL (10, 2) NULL,
    [Coinsurance_amount]                                   DECIMAL (10, 2) NULL,
    [Copay_amount]                                         DECIMAL (10, 2) NULL,
    [COB_amount]                                           DECIMAL (10, 2) NULL,
    [Claim_type]                                           VARCHAR (100)   NULL,
    [Bill Type Code]                                       VARCHAR (100)   NULL,
    [Revenue_code]                                         VARCHAR (100)   NULL,
    [DRG]                                                  BIGINT          NULL,
    [MS_DRG]                                               VARCHAR (100)   NULL,
    [Claim_status]                                         VARCHAR (100)   NULL,
    [Units]                                                VARCHAR (100)   NULL,
    [Diagnosis_code_1]                                     VARCHAR (100)   NULL,
    [Diagnosis_code_2]                                     VARCHAR (100)   NULL,
    [Diagnosis_code_3]                                     VARCHAR (100)   NULL,
    [Diagnosis_code_4]                                     VARCHAR (100)   NULL,
    [Diagnosis_code_5]                                     VARCHAR (100)   NULL,
    [Diagnosis_code_6]                                     VARCHAR (100)   NULL,
    [Diagnosis_code_7]                                     VARCHAR (100)   NULL,
    [Diagnosis_code_8]                                     VARCHAR (100)   NULL,
    [Diagnosis_code_9]                                     VARCHAR (100)   NULL,
    [Diagnosis_code_10]                                    VARCHAR (100)   NULL,
    [Diagnosis_code_11]                                    VARCHAR (100)   NULL,
    [Diagnosis_code_12]                                    VARCHAR (100)   NULL,
    [Diagnosis_code_13]                                    VARCHAR (100)   NULL,
    [Diagnosis_code_14]                                    VARCHAR (100)   NULL,
    [Diagnosis_code_15]                                    VARCHAR (100)   NULL,
    [Diagnosis_code_16]                                    VARCHAR (100)   NULL,
    [Diagnosis_code_17]                                    VARCHAR (100)   NULL,
    [Diagnosis_code_18]                                    VARCHAR (100)   NULL,
    [Diagnosis_code_19]                                    VARCHAR (100)   NULL,
    [Diagnosis_code_20]                                    VARCHAR (100)   NULL,
    [ICD Version]                                          BIGINT          NULL,
    [refering provider ID]                                 VARCHAR (100)   NULL,
    [Billing_provider_id]                                  VARCHAR (100)   NULL,
    [servicing_provider_Id]                                VARCHAR (100)   NULL,
    [Billing_Provider_NPI]                                 VARCHAR (100)   NULL,
    [Servicing_Provider_NPI]                               VARCHAR (100)   NULL,
    [Servicing_provider_specialty code]                    VARCHAR (100)   NULL,
    [Network_ind]                                          VARCHAR (100)   NULL,
    [Network_ID]                                           VARCHAR (100)   NULL,
    [Billed_Amount]                                        VARCHAR (100)   NULL,
    [Company_ID]                                           VARCHAR (100)   NULL,
    [Division_ID]                                          VARCHAR (100)   NULL,
    [Payer_ID]                                             VARCHAR (100)   NULL,
    [Status_ID]                                            VARCHAR (100)   NULL,
    [Employer_Group]                                       VARCHAR (100)   NULL,
    [Medicare_Identifier]                                  VARCHAR (100)   NULL,
    [MDC]                                                  BIGINT          NULL,
    [HOSP_DAYS_CNT]                                        BIGINT          NULL,
    [CLM_RECV_DT]                                          VARCHAR (100)   NULL,
    [Patient_Status]                                       BIGINT          NULL,
    [Payment_Tier_Code]                                    BIGINT          NULL,
    [Services]                                             BIGINT          NULL,
    [Admission_Indicator]                                  BIGINT          NULL,
    [Visit_Indicator]                                      BIGINT          NULL,
    [Claim_Filing_Code]                                    BIGINT          NULL,
    [Claim_Reporting_Category]                             INT             NULL,
    [Policy_Type_Code]                                     BIGINT          NULL,
    [Claim_Origin_Code]                                    VARCHAR (100)   NULL,
    [CCP_Program_Indicator]                                BIGINT          NULL,
    [CCP_Requirement_MET_code]                             BIGINT          NULL,
    [Diagnosis_Classification_Code]                        VARCHAR (100)   NULL,
    [Diagnosis_Category_Code]                              BIGINT          NULL,
    [Adjustment_Sequence_Number]                           BIGINT          NULL,
    [Payee_Code]                                           BIGINT          NULL,
    [Bill_Frequency_Code]                                  BIGINT          NULL,
    [Bill_Institutional_Code]                              BIGINT          NULL,
    [RX_ID]                                                BIGINT          NULL,
    [RX_National_Drug_Code]                                BIGINT          NULL,
    [RX_Drug_Name]                                         VARCHAR (100)   NULL,
    [RX_Drug_Type_Code]                                    BIGINT          NULL,
    [RX_Drug_Category_Code]                                VARCHAR (100)   NULL,
    [RX_Tier_Level_Code]                                   BIGINT          NULL,
    [RX_Therapeutic_Class]                                 BIGINT          NULL,
    [RX_DEA_Number]                                        VARCHAR (100)   NULL,
    [RX_Mail_Order_Indicator]                              VARCHAR (100)   NULL,
    [RX_Dispense_as_Written]                               BIGINT          NULL,
    [RX_Metric_Quantity]                                   DECIMAL (10, 2) NULL,
    [RX_Days_Supply]                                       DECIMAL (10, 2) NULL,
    [RX_Origin_Code]                                       BIGINT          NULL,
    [RX_GPI]                                               VARCHAR (100)   NULL,
    [RX_Generic_Paid_Indicator]                            VARCHAR (100)   NULL,
    [Rx_Chain_Pharmacy_ID]                                 BIGINT          NULL,
    [Rx_Formulary_Drug_Indicator]                          VARCHAR (100)   NULL,
    [RX_Compound_Code]                                     BIGINT          NULL,
    [Ineligible_Reason_Code_1]                             VARCHAR (100)   NULL,
    [Ineligible_Reason_Code_2]                             VARCHAR (100)   NULL,
    [Ineligible_Reason_Code_3]                             VARCHAR (100)   NULL,
    [Sub_SSN]                                              BIGINT          NULL,
    [Sub_Last_Name]                                        VARCHAR (100)   NULL,
    [Sub_First_Name]                                       VARCHAR (100)   NULL,
    [Sub_Gender]                                           VARCHAR (100)   NULL,
    [Sub_DOB]                                              DATE            NULL,
    [Sub_Zip]                                              BIGINT          NULL,
    [Sub_State]                                            VARCHAR (100)   NULL,
    [Patient_First_Name]                                   VARCHAR (100)   NULL,
    [Patient_Last_Name]                                    VARCHAR (100)   NULL,
    [Patiend_DOB]                                          DATE            NULL,
    [Patient_Gender]                                       VARCHAR (100)   NULL,
    [Patient_SSN]                                          BIGINT          NULL,
    [Patient_Relationship]                                 VARCHAR (100)   NULL,
    [Patient_Middle_Name]                                  VARCHAR (100)   NULL,
    [Patient_Zip_Code]                                     BIGINT          NULL,
    [[Servicing_Provider_ID_Format_Code]]]                 VARCHAR (100)   NULL,
    [Servicing_Provider_City]                              VARCHAR (100)   NULL,
    [Servicing_Provider_Street_Address_1]                  VARCHAR (100)   NULL,
    [Servicing_Provider_Street_Address_2]                  VARCHAR (100)   NULL,
    [Servicing_Provider_Name]                              VARCHAR (100)   NULL,
    [Servicing_Provider_State]                             VARCHAR (100)   NULL,
    [Servicing_Provider_Zip_Code]                          VARCHAR (100)   NULL,
    [Servicing_Provider_PIN]                               VARCHAR (100)   NULL,
    [Servicing_Provider_Type]                              VARCHAR (100)   NULL,
    [ENCNTR_IND]                                           VARCHAR (100)   NULL,
    [Line_of_Business_Code]                                VARCHAR (100)   NULL,
    [Hierarchy_Level_1]                                    VARCHAR (100)   NULL,
    [Hierarchy_Level_2]                                    VARCHAR (100)   NULL,
    [Hierarchy_Level_3]                                    BIGINT          NULL,
    [Hierarchy_Level_5]                                    BIGINT          NULL,
    [Hierarchy_Level_6]                                    VARCHAR (100)   NULL,
    [Source_System_Platform]                               VARCHAR (100)   NULL,
    [Adjustment_Code]                                      VARCHAR (100)   NULL,
    [Preferred_vs_Non-Preferred_Benefit_Level]             VARCHAR (100)   NULL,
    [General_Category_of_Health_Plan]                      VARCHAR (100)   NULL,
    [Classification_Code]                                  VARCHAR (100)   NULL,
    [Benefit_Identification_Code]                          VARCHAR (100)   NULL,
    [Plan_Code_or_Extension_of_Hierarchy]                  VARCHAR (100)   NULL,
    [Benefit_Tier]                                         VARCHAR (100)   NULL,
    [Funding_Arrangement]                                  VARCHAR (100)   NULL,
    [Coverage_OR_Enrollment_Tier]                          VARCHAR (100)   NULL,
    [Member_Relationship_to_Subscriber]                    VARCHAR (100)   NULL,
    [Source-Specific_Transaction_ID_Number]                VARCHAR (100)   NULL,
    [ACAS_Generation_OR_Segment_Number]                    VARCHAR (100)   NULL,
    [ACAS_Pointer_Back_to_Previous_Gen_OR_Seg]             VARCHAR (100)   NULL,
    [Claim_Line_ID_Assigned_in_Data_Warehouse]             VARCHAR (100)   NULL,
    [Subscriber_Network_ID]                                VARCHAR (100)   NULL,
    [Servicing_Provider_Network_ID]                        VARCHAR (100)   NULL,
    [Referral_Type]                                        VARCHAR (100)   NULL,
    [PCPs_IRS_Tax_Identification_Number_Format_Code]       VARCHAR (100)   NULL,
    [PCPs_IRS_Tax_Identification_Number]                   VARCHAR (100)   NULL,
    [PCP's_Name_(Last_or_Full)]                            VARCHAR (100)   NULL,
    [Assignment_of_Benefits_to_Provider_Code]              VARCHAR (100)   NULL,
    [Participating_Provider_Code]                          VARCHAR (100)   NULL,
    [Date_Processed_(Non-HMO_Only)]                        VARCHAR (100)   NULL,
    [Service_Benefit_Code_*]                               VARCHAR (100)   NULL,
    [Tooth_Number]                                         VARCHAR (100)   NULL,
    [Source_Number/Units_of_Service]                       VARCHAR (100)   NULL,
    [Gross_Submitted_Expense__***]                         VARCHAR (100)   NULL,
    [Net_Submitted_Expense__***]                           VARCHAR (100)   NULL,
    [Not_Covered_Amount_1]                                 VARCHAR (100)   NULL,
    [Not_Covered_Amount_2]                                 VARCHAR (100)   NULL,
    [Not_Covered_Amount_3]                                 VARCHAR (100)   NULL,
    [Action_or_Reason_Code_1]                              VARCHAR (100)   NULL,
    [Action_or_Reason_Code_2]                              VARCHAR (100)   NULL,
    [Action_or_Reason_Code_3]                              VARCHAR (100)   NULL,
    [Covered_Expense]                                      VARCHAR (100)   NULL,
    [Source_Copayment_Amount]                              VARCHAR (100)   NULL,
    [Source_Coinsurance_Amount]                            VARCHAR (100)   NULL,
    [Benefit_Payable]                                      VARCHAR (100)   NULL,
    [Aetna_Health_Fund_-_Before_Fund_Deductible]           VARCHAR (100)   NULL,
    [Aetna_Health_Fund_-_Payable_Amount]                   VARCHAR (100)   NULL,
    [Savings_-_Negotiated_Fee__***]                        VARCHAR (100)   NULL,
    [Savings_-_R&C]                                        VARCHAR (100)   NULL,
    [Savings_-_COB]                                        VARCHAR (100)   NULL,
    [Savings_-_Source_COB]                                 VARCHAR (100)   NULL,
    [Medicare_Code]                                        VARCHAR (100)   NULL,
    [Type_of_Expense_-_COB]                                VARCHAR (100)   NULL,
    [COB_Code]                                             VARCHAR (100)   NULL,
    [National_Drug_Code_*]                                 VARCHAR (100)   NULL,
    [Member_'CUMBID']                                      VARCHAR (100)   NULL,
    [Non-SSN_Subscriber_ID]                                VARCHAR (100)   NULL,
    [Reversal_Code]                                        VARCHAR (100)   NULL,
    [Administrative_Savings_Amount]                        VARCHAR (100)   NULL,
    [Aexcel_Provider_Designation_Code]                     VARCHAR (100)   NULL,
    [Aexcel_Plan_Design_Code]                              VARCHAR (100)   NULL,
    [Aexcel_Benefit_Tier_Code]                             VARCHAR (100)   NULL,
    [Aexcel_Designated_Provider_Specialty]                 VARCHAR (100)   NULL,
    [Product_Distinction_Code]                             VARCHAR (100)   NULL,
    [Billed_Eligible_Amount_(DO_NOT_USE_IF_UNMASKED)]      VARCHAR (100)   NULL,
    [Servicing_Provider_Class_Code_*]                      VARCHAR (100)   NULL,
    [Present_on_Admission_Code_(1)_*]                      VARCHAR (100)   NULL,
    [Present_on_Admission_Code_(2)_*]                      VARCHAR (100)   NULL,
    [Present_on_Admission_Code_(3)_*]                      VARCHAR (100)   NULL,
    [Pricing_Method_Code]                                  VARCHAR (100)   NULL,
    [Servicing_Provider_Type_Class_Code]                   VARCHAR (100)   NULL,
    [Servicing_Provider_Specialty_Category_Code_*]         VARCHAR (100)   NULL,
    [Total_Deductible_Met_Indicator]                       VARCHAR (100)   NULL,
    [Total_Interest_Amount]                                VARCHAR (100)   NULL,
    [Total_Surcharge_Amount]                               VARCHAR (100)   NULL,
    [HCFA_Place_of_Service_Code_*]                         VARCHAR (100)   NULL,
    [Line-Level_Procedure_Code_Modifier_(2)_*]             VARCHAR (100)   NULL,
    [Line-Level_Procedure_Code_Modifier_(3)_*]             VARCHAR (100)   NULL,
    [Present_on_Admission_Code_(4)_*]                      VARCHAR (100)   NULL,
    [Present_on_Admission_Code_(5)_*]                      VARCHAR (100)   NULL,
    [Present_on_Admission_Code_(6)_*]                      VARCHAR (100)   NULL,
    [Present_on_Admission_Code_(7)_*]                      VARCHAR (100)   NULL,
    [Present_on_Admission_Code_(8)_*]                      VARCHAR (100)   NULL,
    [Present_on_Admission_Code_(9)_*]                      VARCHAR (100)   NULL,
    [Present_on_Admission_Code_(10)_*]                     VARCHAR (100)   NULL,
    [ICD_Procedure_Code_6_*]                               VARCHAR (100)   NULL,
    [Aetna_Health_Fund_Determination_Order_Code]           VARCHAR (100)   NULL,
    [Aetna_Health_Fund_Member_Share_of_Coinsurance_Amount] VARCHAR (100)   NULL,
    [Aetna_Health_Fund_Member_Copay_Amount]                VARCHAR (100)   NULL,
    [Aetna_Health_Fund_Member_Deductible_Amount]           VARCHAR (100)   NULL,
    [Exchange_ID]                                          VARCHAR (100)   NULL,
    [Claim_Extention]                                      VARCHAR (100)   NULL,
    [Debit_Credit_Code]                                    VARCHAR (100)   NULL,
    [Disposition_Code]                                     VARCHAR (100)   NULL,
    [Procedure_Code3]                                      VARCHAR (100)   NULL,
    [Procedure_Code3_Type]                                 VARCHAR (100)   NULL,
    [Procedure_Code4]                                      VARCHAR (100)   NULL,
    [Procedure_Code4_Type]                                 VARCHAR (100)   NULL,
    [Procedure_Code5]                                      VARCHAR (100)   NULL,
    [Procedure_Code5_Type]                                 VARCHAR (100)   NULL,
    [Trans_Code]                                           VARCHAR (100)   NULL,
    [Adjustment_Type]                                      VARCHAR (100)   NULL,
    [Approved/Denied_code]                                 VARCHAR (100)   NULL,
    [Capitated_service_indicator]                          VARCHAR (100)   NULL,
    [Department_number]                                    VARCHAR (100)   NULL,
    [CDHP_HRA_Amount]                                      VARCHAR (100)   NULL,
    [Non_covered_amount]                                   VARCHAR (100)   NULL,
    [PCP_Indicator]                                        VARCHAR (100)   NULL,
    [PCP_Zip_code]                                         VARCHAR (100)   NULL,
    [Person_ID]                                            VARCHAR (100)   NULL,
    [Package_number]                                       VARCHAR (100)   NULL,
    [Product_ID]                                           VARCHAR (100)   NULL,
    [Servicing_Provider_Tax_ID]                            VARCHAR (100)   NULL,
    [Subscriber_ID]                                        VARCHAR (100)   NULL,
    [Employee_coverage_type]                               VARCHAR (100)   NULL,
    [Subgroup_number]                                      VARCHAR (100)   NULL,
    [Date_Inserted]                                        DATETIME        DEFAULT (getdate()) NOT NULL,
    [Date_Updated]                                         DATETIME        DEFAULT (getdate()) NOT NULL,
    [Carrier]                                              VARCHAR (50)    NULL,
    [Client]                                               VARCHAR (50)    NULL,
    [run_instance_skey]                                    INT             NULL,
    [source_file_skey]                                     INT             NULL,
    [Month]                                                INT             NULL,
    [Year]                                                 INT             NULL,
    PRIMARY KEY CLUSTERED ([S.No.] ASC)
);


GO
CREATE NONCLUSTERED INDEX [idx_stg_claim_account_no]
    ON [stg].[Arch_tbl_medical_claim]([Account_Number] ASC);

