CREATE TABLE [stg].[error_tbl_member] (
    [member_key]                     BIGINT        NOT NULL,
    [account_nbr]                    BIGINT        NOT NULL,
    [group_nbr]                      BIGINT        NOT NULL,
    [section_nbr]                    BIGINT        NOT NULL,
    [contract_type]                  VARCHAR (100) NOT NULL,
    [product_line]                   INT           NOT NULL,
    [product_type]                   VARCHAR (10)  NOT NULL,
    [subscriber_id]                  BIGINT        NOT NULL,
    [subscriber_ssn]                 BIGINT        NULL,
    [member_ssn]                     BIGINT        NULL,
    [member_nbr]                     BIGINT        NULL,
    [client_member_id]               BIGINT        NOT NULL,
    [member_dob]                     DATETIME      NULL,
    [member_gender]                  CHAR (1)      NULL,
    [member_relationship_code]       CHAR (1)      NULL,
    [member_status]                  VARCHAR (50)  NULL,
    [member_medicare_status_code]    CHAR (1)      NULL,
    [member_first_name]              VARCHAR (50)  NULL,
    [member_last_name]               VARCHAR (60)  NULL,
    [member_original_effective_date] DATETIME      NOT NULL,
    [member_phone]                   VARCHAR (10)  NULL,
    [member_email]                   VARCHAR (50)  NULL,
    [subscriber_address]             TEXT          NULL,
    [subscriber_city]                VARCHAR (50)  NULL,
    [subscriber_state]               VARCHAR (50)  NULL,
    [subscriber_zip]                 VARCHAR (10)  NULL,
    [member_effective_date]          DATETIME      NOT NULL,
    [member_cancel_date]             DATETIME      NOT NULL,
    [benefit_agreement]              VARCHAR (100) NULL,
    [characteristic_code_1]          VARCHAR (10)  NULL,
    [characteristic_description_1]   TEXT          NULL,
    [characteristic_code_2]          VARCHAR (10)  NULL,
    [characteristic_description_2]   TEXT          NULL,
    [characteristic_code_3]          VARCHAR (10)  NULL,
    [characteristic_description_3]   TEXT          NULL,
    [characteristic_code_4]          VARCHAR (10)  NULL,
    [characteristic_description_4]   TEXT          NULL,
    [characteristic_code_5]          VARCHAR (10)  NULL,
    [characteristic_description_5]   TEXT          NULL,
    [characteristic_code_6]          VARCHAR (10)  NULL,
    [characteristic_description_6]   TEXT          NULL,
    [run_instance_skey]              BIGINT        NOT NULL,
    [source_file_skey]               BIGINT        NOT NULL,
    [stg_inserted_timestamp]         DATETIME      NOT NULL
);

