CREATE TABLE [stg].[tbl_medical_claim_aetna] (
    [ps_unique_id]                                    VARCHAR (16)    NULL,
    [customer_nbr]                                    VARCHAR (8)     NULL,
    [group_nbr]                                       VARCHAR (8)     NULL,
    [FILLER_1]                                        VARCHAR (3)     NULL,
    [subgroup_nbr]                                    VARCHAR (8)     NULL,
    [account_nbr]                                     VARCHAR (5)     NULL,
    [file_id]                                         VARCHAR (2)     NULL,
    [clm_ln_type_cd]                                  VARCHAR (1)     NULL,
    [non_prfrrd_srv_cd]                               VARCHAR (1)     NULL,
    [plsp_prod_cd]                                    VARCHAR (2)     NULL,
    [product_ln_cd]                                   VARCHAR (2)     NULL,
    [classification_cd]                               VARCHAR (1)     NULL,
    [bnft_pkg_id]                                     VARCHAR (5)     NULL,
    [plan_id]                                         VARCHAR (5)     NULL,
    [benefit_tier]                                    VARCHAR (1)     NULL,
    [fund_ctg_cd]                                     VARCHAR (1)     NULL,
    [src_subscriber_id]                               VARCHAR (11)    NULL,
    [subscriber_last_nm]                              VARCHAR (30)    NULL,
    [subscriber_first_nm]                             VARCHAR (30)    NULL,
    [gender_cd]                                       VARCHAR (1)     NULL,
    [subscriber_brth_dt]                              DATE            NULL,
    [subs_zip_cd]                                     VARCHAR (5)     NULL,
    [subs_st_postal_cd]                               VARCHAR (2)     NULL,
    [coverage_type_cd]                                VARCHAR (1)     NULL,
    [ssn_nbr]                                         VARCHAR (11)    NULL,
    [member_id]                                       VARCHAR (20)    NULL,
    [member_number]                                   VARCHAR (2)     NULL,
    [member_last_nm]                                  VARCHAR (30)    NULL,
    [member_first_nm]                                 VARCHAR (30)    NULL,
    [mbr_gender_cd]                                   VARCHAR (1)     NULL,
    [mbr_rtp_type_cd]                                 VARCHAR (1)     NULL,
    [birth_dt]                                        DATE            NULL,
    [src_clm_id]                                      VARCHAR (19)    NULL,
    [acas_gen_seq_nbr]                                VARCHAR (2)     NULL,
    [prev_clm_seg_id]                                 VARCHAR (2)     NULL,
    [derived_tcn_nbr]                                 VARCHAR (15)    NULL,
    [src_claim_line_id]                               VARCHAR (3)     NULL,
    [claim_line_id]                                   BIGINT          NULL,
    [ntwk_srv_area_id]                                VARCHAR (5)     NULL,
    [paid_prvdr_nsa_id]                               VARCHAR (5)     NULL,
    [srv_capacity_cd]                                 VARCHAR (1)     NULL,
    [PCP IRS tax_id_format_cd]                        VARCHAR (1)     NULL,
    [PCP IRS tax_id_nbr]                              VARCHAR (9)     NULL,
    [PCP IRS print_nm]                                VARCHAR (40)    NULL,
    [srv_prvdr_tax_id_format_cd]                      VARCHAR (1)     NULL,
    [srv_prvdr_tax_id_nbr]                            VARCHAR (9)     NULL,
    [srv_prvdr_id]                                    BIGINT          NULL,
    [srv_prvdr_print_nm]                              VARCHAR (40)    NULL,
    [address_line_1_txt]                              VARCHAR (35)    NULL,
    [address_line_2_txt]                              VARCHAR (35)    NULL,
    [city_nm]                                         VARCHAR (30)    NULL,
    [state_postal_cd]                                 VARCHAR (2)     NULL,
    [zip_cd]                                          VARCHAR (5)     NULL,
    [provider_type_cd]                                VARCHAR (3)     NULL,
    [specialty_cd]                                    VARCHAR (5)     NULL,
    [payee_cd]                                        VARCHAR (1)     NULL,
    [paid_prvdr_par_cd]                               VARCHAR (1)     NULL,
    [received_dt]                                     DATE            NULL,
    [adjn_dt]                                         DATE            NULL,
    [srv_start_dt]                                    DATE            NULL,
    [srv_stop_dt]                                     DATE            NULL,
    [paid_dt for file_id 03 else adjn_dt for file_id] DATE            NULL,
    [FILLER_2]                                        VARCHAR (6)     NULL,
    [FILLER_3]                                        VARCHAR (6)     NULL,
    [FILLER_4]                                        VARCHAR (6)     NULL,
    [mdc_cd]                                          VARCHAR (2)     NULL,
    [drg_cd]                                          VARCHAR (3)     NULL,
    [prcdr_cd]                                        VARCHAR (5)     NULL,
    [prcdr_modifier_cd]                               VARCHAR (2)     NULL,
    [prcdr_type_cd]                                   VARCHAR (1)     NULL,
    [FILLER_5]                                        VARCHAR (5)     NULL,
    [FILLER_6]                                        VARCHAR (5)     NULL,
    [FILLER_7]                                        VARCHAR (5)     NULL,
    [type_srv_cd]                                     VARCHAR (2)     NULL,
    [benefit_cd]                                      VARCHAR (3)     NULL,
    [tooth_1_nbr]                                     VARCHAR (5)     NULL,
    [plc_srv_cd]                                      VARCHAR (2)     NULL,
    [dschrg_status_cd]                                VARCHAR (2)     NULL,
    [revenue_cd]                                      VARCHAR (4)     NULL,
    [hcfa_bill_type_cd]                               VARCHAR (3)     NULL,
    [unit_cnt]                                        DECIMAL (11, 3) NULL,
    [src_unit_cnt]                                    DECIMAL (11, 3) NULL,
    [src_billed_amt]                                  DECIMAL (11, 3) NULL,
    [billed_amt]                                      DECIMAL (11, 3) NULL,
    [not_covered_amt (1)]                             DECIMAL (11, 3) NULL,
    [not_covered_amt (2)]                             DECIMAL (11, 3) NULL,
    [not_covered_amt (3)]                             DECIMAL (11, 3) NULL,
    [clm_ln_msg_cd (1)]                               VARCHAR (4)     NULL,
    [clm_ln_msg_cd (2)]                               VARCHAR (4)     NULL,
    [clm_ln_msg_cd (3)]                               VARCHAR (4)     NULL,
    [covered_amt]                                     DECIMAL (11, 3) NULL,
    [allowed_amt]                                     DECIMAL (11, 3) NULL,
    [FILLER_8]                                        VARCHAR (10)    NULL,
    [srv_copay_amt]                                   DECIMAL (11, 3) NULL,
    [src_srv_copay_amt]                               DECIMAL (11, 3) NULL,
    [deductible_amt]                                  DECIMAL (11, 3) NULL,
    [coinsurance_amt]                                 DECIMAL (11, 3) NULL,
    [src_coins_amt]                                   DECIMAL (11, 3) NULL,
    [bnft_payable_amt]                                DECIMAL (11, 3) NULL,
    [paid_amt]                                        DECIMAL (11, 3) NULL,
    [cob_paid_amt]                                    DECIMAL (11, 3) NULL,
    [ahf_bfd_amt]                                     DECIMAL (11, 3) NULL,
    [ahf_paid_amt]                                    DECIMAL (11, 3) NULL,
    [negot_savings_amt]                               DECIMAL (11, 3) NULL,
    [r_c_savings_amt]                                 DECIMAL (11, 3) NULL,
    [cob_savings_amt]                                 DECIMAL (11, 3) NULL,
    [src_cob_svngs_amt]                               DECIMAL (11, 3) NULL,
    [pri_payer_cvg_cd]                                VARCHAR (1)     NULL,
    [cob_type_cd]                                     VARCHAR (1)     NULL,
    [cob_cd]                                          VARCHAR (1)     NULL,
    [prcdr_cd_ndc]                                    VARCHAR (11)    NULL,
    [src_clm_mbr_id]                                  VARCHAR (22)    NULL,
    [clm_ln_status_cd]                                VARCHAR (1)     NULL,
    [src_member_id]                                   VARCHAR (22)    NULL,
    [reversal_cd]                                     VARCHAR (2)     NULL,
    [admit_cnt]                                       VARCHAR (2)     NULL,
    [admin_savings_amt]                               DECIMAL (11, 3) NULL,
    [adj_prvdr_dsgnn_cd]                              VARCHAR (3)     NULL,
    [aex_plan_dsgntn_cd]                              VARCHAR (1)     NULL,
    [benefit_tier_cd]                                 VARCHAR (2)     NULL,
    [aex_prvdr_spctg_cd]                              VARCHAR (4)     NULL,
    [prod_distnctn_cd]                                VARCHAR (1)     NULL,
    [billed_eligible_amt]                             DECIMAL (11, 3) NULL,
    [srv_provider_class_cd]                           VARCHAR (3)     NULL,
    [poa_cd (1)]                                      VARCHAR (1)     NULL,
    [poa_cd (2)]                                      VARCHAR (1)     NULL,
    [poa_cd (3)]                                      VARCHAR (1)     NULL,
    [FILLER_9]                                        VARCHAR (6)     NULL,
    [FILLER_10]                                       VARCHAR (6)     NULL,
    [FILLER_11]                                       VARCHAR (6)     NULL,
    [pricing_mthd_cd]                                 VARCHAR (1)     NULL,
    [type_class_cd]                                   VARCHAR (1)     NULL,
    [specialty_ctg_cd]                                VARCHAR (4)     NULL,
    [srv_prvdr_npi]                                   VARCHAR (20)    NULL,
    [ttl_ded_met_ind]                                 VARCHAR (1)     NULL,
    [ttl_interest_amt]                                DECIMAL (11, 3) NULL,
    [ttl_surcharge_amt]                               DECIMAL (11, 3) NULL,
    [FILLER_12]                                       VARCHAR (4)     NULL,
    [hcfa_plc_srv_cd]                                 VARCHAR (2)     NULL,
    [hcfa_admit_src_cd]                               VARCHAR (1)     NULL,
    [hcfa_admit_type_cd]                              VARCHAR (1)     NULL,
    [src_admit_dt]                                    VARCHAR (10)    NULL,
    [src_discharge_dt]                                VARCHAR (10)    NULL,
    [prcdr_modifier_cd(2)]                            VARCHAR (2)     NULL,
    [prcdr_modifier_cd(3)]                            VARCHAR (2)     NULL,
    [poa_cd (4)]                                      VARCHAR (1)     NULL,
    [poa_cd (5)]                                      VARCHAR (1)     NULL,
    [poa_cd (6)]                                      VARCHAR (1)     NULL,
    [poa_cd (7)]                                      VARCHAR (1)     NULL,
    [poa_cd (8)]                                      VARCHAR (1)     NULL,
    [poa_cd (9)]                                      VARCHAR (1)     NULL,
    [poa_cd (10)]                                     VARCHAR (1)     NULL,
    [pri_icd9_dx_cd]                                  VARCHAR (8)     NULL,
    [icd9_dx_cd (2)]                                  VARCHAR (8)     NULL,
    [icd9_dx_cd (3)]                                  VARCHAR (8)     NULL,
    [icd9_dx_cd (4)]                                  VARCHAR (8)     NULL,
    [icd9_dx_cd (5)]                                  VARCHAR (8)     NULL,
    [icd9_dx_cd (6)]                                  VARCHAR (8)     NULL,
    [icd9_dx_cd (7)]                                  VARCHAR (8)     NULL,
    [icd9_dx_cd (8)]                                  VARCHAR (8)     NULL,
    [icd9_dx_cd (9)]                                  VARCHAR (8)     NULL,
    [icd9_dx_cd (10)]                                 VARCHAR (8)     NULL,
    [icd9_prcdr_cd (1)]                               VARCHAR (7)     NULL,
    [icd9_prcdr_cd (2)]                               VARCHAR (7)     NULL,
    [icd9_prcdr_cd (3)]                               VARCHAR (7)     NULL,
    [icd9_prcdr_cd (4)]                               VARCHAR (7)     NULL,
    [icd9_prcdr_cd (5)]                               VARCHAR (7)     NULL,
    [icd9_prcdr_cd (6)]                               VARCHAR (7)     NULL,
    [ahf_det_order_cd]                                VARCHAR (3)     NULL,
    [ahf_mbr_coins_amt]                               DECIMAL (11, 3) NULL,
    [ahf_mbr_copay_amt]                               DECIMAL (11, 3) NULL,
    [ahf_mbr_ded_amt]                                 DECIMAL (11, 3) NULL,
    [FILLER_13]                                       VARCHAR (1)     NULL,
    [FILLER_14]                                       VARCHAR (1)     NULL,
    [icd-10_ind]                                      VARCHAR (1)     NULL,
    [xchng_id (org_id)]                               VARCHAR (9)     NULL,
    [FILLER_15]                                       VARCHAR (8)     NULL,
    [not applicable]                                  VARCHAR (1)     NULL
);

