CREATE TABLE [stg].[tbl_eligibility] (
    [seq_id]                          INT           IDENTITY (1, 1) NOT NULL,
    [member_id]                       VARCHAR (100) NULL,
    [employee_id]                     BIGINT        NULL,
    [first_name]                      VARCHAR (100) NULL,
    [last_name]                       VARCHAR (100) NULL,
    [relationship_code]               VARCHAR (100) NULL,
    [member_date_of_birth]            DATETIME      NULL,
    [member_gender]                   VARCHAR (100) NULL,
    [plan_id]                         VARCHAR (100) NULL,
    [member_status]                   VARCHAR (100) NULL,
    [benefit_coverage_effective_date] DATETIME      NULL,
    [benefit_coverage_end_date]       DATETIME      NULL,
    [reason_for_end]                  VARCHAR (100) NULL,
    [ssn]                             BIGINT        NULL,
    [pharmacy_indicator]              VARCHAR (100) NULL,
    [home_phone]                      VARCHAR (100) NULL,
    [cell_phone]                      VARCHAR (100) NULL,
    [email]                           VARCHAR (100) NULL,
    [address]                         VARCHAR (100) NULL,
    [city]                            VARCHAR (100) NULL,
    [state]                           VARCHAR (100) NULL,
    [zip]                             VARCHAR (100) NULL,
    [pcp_id]                          VARCHAR (100) NULL,
    [medicare_indicator]              VARCHAR (100) NULL,
    [subscriber_ssn]                  BIGINT        NULL,
    [member_middle_initial]           VARCHAR (100) NULL,
    [account_number]                  BIGINT        NULL,
    [branch]                          VARCHAR (100) NULL,
    [account_type]                    VARCHAR (100) NULL,
    [account_subtype]                 VARCHAR (100) NULL,
    [account_subtype_2]               VARCHAR (100) NULL,
    [member_month_year_month]         VARCHAR (100) NULL,
    [member_address_line_2]           VARCHAR (100) NULL,
    [subscriber_first_name]           VARCHAR (100) NULL,
    [subscriber_middle_initial]       VARCHAR (100) NULL,
    [subscriber_last_name]            VARCHAR (100) NULL,
    [subscriber_birth_date]           VARCHAR (100) NULL,
    [subscriber_sex]                  VARCHAR (100) NULL,
    [subscriber_address]              VARCHAR (100) NULL,
    [subscriber_city]                 VARCHAR (100) NULL,
    [subscriber_state]                VARCHAR (100) NULL,
    [subscriber_zip]                  BIGINT        NULL,
    [group_number]                    BIGINT        NULL,
    [section_number]                  BIGINT        NULL,
    [contract_type]                   VARCHAR (100) NULL,
    [product_line]                    VARCHAR (100) NULL,
    [product_type]                    VARCHAR (100) NULL,
    [client_member_id]                VARCHAR (100) NULL,
    [member_original_effective_date]  DATETIME      NULL,
    [benefit_agreement]               VARCHAR (100) NULL,
    [characteristic_code_1]           VARCHAR (100) NULL,
    [characteristic_description_1]    VARCHAR (100) NULL,
    [characteristic_code_2]           VARCHAR (100) NULL,
    [characteristic_description_2]    VARCHAR (100) NULL,
    [characteristic_code_3]           VARCHAR (100) NULL,
    [characteristic_description_3]    VARCHAR (100) NULL,
    [characteristic_code_4]           VARCHAR (100) NULL,
    [characteristic_description_4]    VARCHAR (100) NULL,
    [characteristic_code_5]           VARCHAR (100) NULL,
    [characteristic_description_5]    VARCHAR (100) NULL,
    [characteristic_code_6]           VARCHAR (100) NULL,
    [characteristic_description_6]    VARCHAR (100) NULL,
    [date_inserted]                   DATETIME      DEFAULT (getdate()) NULL,
    [date_updated]                    DATETIME      DEFAULT (getdate()) NULL,
    [carrier]                         VARCHAR (50)  NULL,
    [client]                          VARCHAR (50)  NULL,
    [run_instance_skey]               INT           NULL,
    [source_file_skey]                INT           NULL,
    [month]                           INT           NULL,
    [year]                            INT           NULL,
    PRIMARY KEY CLUSTERED ([seq_id] ASC)
);

