CREATE TABLE [stg].[tbl_pharmacy_claim] (
    [pharmacy_claim_skey]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [member_id]                 BIGINT          NOT NULL,
    [claim_id]                  BIGINT          NOT NULL,
    [ndc]                       VARCHAR (20)    NULL,
    [fill_date]                 DATETIME        NULL,
    [paid_date]                 DATETIME        NULL,
    [days_supply]               BIGINT          NULL,
    [quantity_dispensed]        BIGINT          NULL,
    [refill_indicator]          VARCHAR (20)    NULL,
    [drug_unit_of_measure]      VARCHAR (20)    NULL,
    [generic_drug_indicator]    VARCHAR (20)    NULL,
    [in_Out_network_indicator]  VARCHAR (20)    NULL,
    [mail_order_indicator]      VARCHAR (20)    NULL,
    [paid_amount]               DECIMAL (10, 5) NULL,
    [allowed_amount]            DECIMAL (10, 5) NULL,
    [coinsurance]               DECIMAL (10, 5) NULL,
    [copay]                     DECIMAL (10, 5) NULL,
    [prescribing_provider_id]   VARCHAR (50)    NULL,
    [claim_status]              VARCHAR (20)    NULL,
    [compound_code]             VARCHAR (20)    NULL,
    [dispensed_as_written]      VARCHAR (20)    NULL,
    [drug_product_name]         VARCHAR (100)   NULL,
    [drug_strength_measurement] VARCHAR (20)    NULL,
    [formulary_indicator]       VARCHAR (20)    NULL,
    [maintenance_indicator]     VARCHAR (20)    NULL,
    [pharmacy_identifier]       VARCHAR (20)    NULL,
    [prescription_fill_number]  BIGINT          NULL,
    [prescription_number]       VARCHAR (20)    NULL,
    [prescription_written_date] DATETIME        NULL,
    [year]                      INT             NOT NULL,
    [month]                     INT             NOT NULL,
    [client_name]               TEXT            NOT NULL,
    [carrier_name]              TEXT            NOT NULL,
    [run_instance_skey]         BIGINT          NOT NULL,
    [source_file_skey]          BIGINT          NOT NULL,
    [stg_inserted_timestamp]    DATETIME        NOT NULL
);

