CREATE TABLE [stg].[tbl_eligibility_cigna] (
    [Member Number]             VARCHAR (11) NULL,
    [Member First Name]         VARCHAR (20) NULL,
    [Member Middle Initial]     VARCHAR (1)  NULL,
    [Member Last Name]          VARCHAR (30) NULL,
    [Member Birth Date]         DATE         NULL,
    [Member Relationship Code]  VARCHAR (1)  NULL,
    [Subscriber SSN]            BIGINT       NULL,
    [Account Number]            VARCHAR (14) NULL,
    [Benefit Plan Number]       VARCHAR (10) NULL,
    [Branch]                    VARCHAR (8)  NULL,
    [Account Type]              VARCHAR (10) NULL,
    [Account Subtype]           VARCHAR (10) NULL,
    [Account Subtype 2]         VARCHAR (6)  NULL,
    [Benefit Plan Number - 2]   VARCHAR (30) NULL,
    [Plan Type]                 VARCHAR (6)  NULL,
    [Member Sex]                VARCHAR (1)  NULL,
    [Street-1]                  VARCHAR (40) NULL,
    [Street-2]                  VARCHAR (40) NULL,
    [City]                      VARCHAR (30) NULL,
    [State]                     VARCHAR (2)  NULL,
    [Zip Code]                  VARCHAR (10) NULL,
    [Subscriber First Name]     VARCHAR (20) NULL,
    [Subscriber Middle Initial] VARCHAR (1)  NULL,
    [Subscriber Last Name]      VARCHAR (30) NULL,
    [Subscriber Birth Date]     DATE         NULL,
    [Subscriber Sex]            VARCHAR (1)  NULL,
    [Subscriber Status Code]    VARCHAR (1)  NULL,
    [Coverage Level]            VARCHAR (1)  NULL,
    [PCP Physician]             VARCHAR (30) NULL,
    [PCP Effective Date]        VARCHAR (10) NULL,
    [PCP Cancel Date]           VARCHAR (10) NULL
);

