CREATE TABLE [stg].[tbl_medical_claim_BCBS_FL_sequa] (
    [GROUP-PRFX]            VARCHAR (2)     NULL,
    [GROUP-BASE]            VARCHAR (5)     NULL,
    [GROUP-SUFX]            VARCHAR (2)     NULL,
    [SUBSCR-ID]             VARCHAR (12)    NULL,
    [PAT-ID]                VARCHAR (3)     NULL,
    [RELATIONSHIP]          VARCHAR (1)     NULL,
    [CLAIM-NO]              VARCHAR (19)    NULL,
    [SUB-CLM-NO]            VARCHAR (2)     NULL,
    [CLM-ADJ-NO]            VARCHAR (2)     NULL,
    [ITS-SERIAL-NO]         VARCHAR (16)    NULL,
    [FILLER_1]              VARCHAR (2)     NULL,
    [DTE-SRVC-BEG]          VARCHAR (10)    NULL,
    [DTE-SRVC-END]          VARCHAR (10)    NULL,
    [DTE-RECVD]             VARCHAR (10)    NULL,
    [DTE-PROCS]             VARCHAR (10)    NULL,
    [DTE-DISP]              VARCHAR (10)    NULL,
    [SUBS-LNAME]            VARCHAR (20)    NULL,
    [SUBS-FNAME]            VARCHAR (10)    NULL,
    [PAT-LNAME]             VARCHAR (20)    NULL,
    [PAT-FNAME]             VARCHAR (20)    NULL,
    [FULL-PAT-DOB]          VARCHAR (10)    NULL,
    [SUBS-ADDRESS1]         VARCHAR (30)    NULL,
    [SUBS-ADDRESS2]         VARCHAR (30)    NULL,
    [SUBS-ADDRESS3]         VARCHAR (30)    NULL,
    [SUBS-CITY]             VARCHAR (20)    NULL,
    [SUBS-STATE]            VARCHAR (5)     NULL,
    [SUBS-ZIP-CD]           VARCHAR (9)     NULL,
    [PROVIDER-NO]           VARCHAR (25)    NULL,
    [PRVDR-SPECLTY]         VARCHAR (2)     NULL,
    [PROVDR-TYPE]           VARCHAR (1)     NULL,
    [PAY-TO-CD]             VARCHAR (1)     NULL,
    [RPT-PLACE-TRTMT]       VARCHAR (1)     NULL,
    [RPT-TYP-OF-SRVC]       VARCHAR (1)     NULL,
    [BIILL TYPE]            VARCHAR (4)     NULL,
    [FILLER_2]              VARCHAR (13)    NULL,
    [FILLER_3]              VARCHAR (2)     NULL,
    [ICD VERSION- SUB]      VARCHAR (1)     NULL,
    [ICD VERSION- ADJ]      VARCHAR (1)     NULL,
    [DRG-DRUG-NO]           VARCHAR (3)     NULL,
    [AMMS-DIAG-CD]          VARCHAR (5)     NULL,
    [UB82-PRIM-DIAG-CD]     VARCHAR (5)     NULL,
    [DRG-CD2]               VARCHAR (5)     NULL,
    [DRG-CD3]               VARCHAR (5)     NULL,
    [DRG-CD4]               VARCHAR (5)     NULL,
    [DRG-CD5]               VARCHAR (5)     NULL,
    [PRIM-PROC-CD-GUCA]     VARCHAR (5)     NULL,
    [GUCA-MOD1]             VARCHAR (5)     NULL,
    [GUCA-MOD2]             VARCHAR (5)     NULL,
    [UB82-PROC-CD1]         VARCHAR (4)     NULL,
    [UB82-PROC-CD2]         VARCHAR (4)     NULL,
    [UB82-PROC-CD3]         VARCHAR (4)     NULL,
    [UB82-PROC-CD4]         VARCHAR (4)     NULL,
    [UB82-PROC-CD5]         VARCHAR (4)     NULL,
    [HCPCS-CD]              VARCHAR (5)     NULL,
    [HCPCS-MOD1]            VARCHAR (5)     NULL,
    [HCPCS-MOD2]            VARCHAR (5)     NULL,
    [AMMS-STAT-CD]          VARCHAR (5)     NULL,
    [FILLER_4]              VARCHAR (2)     NULL,
    [PRIM-DIAG-ICD10]       VARCHAR (7)     NULL,
    [UB82-ADMIT-DIAG-ICD10] VARCHAR (7)     NULL,
    [IDC10-DIAG-CD1]        VARCHAR (7)     NULL,
    [IDC10-DIAG-CD2]        VARCHAR (7)     NULL,
    [IDC10-DIAG-CD3]        VARCHAR (7)     NULL,
    [IDC10-DIAG-CD4]        VARCHAR (7)     NULL,
    [ORIG-PROC-ICD10]       VARCHAR (7)     NULL,
    [SEC-PROC-ICD10-01]     VARCHAR (7)     NULL,
    [SEC-PROC-ICD10-02]     VARCHAR (7)     NULL,
    [SEC-PROC-ICD10-03]     VARCHAR (7)     NULL,
    [SEC-PROC-ICD10-04]     VARCHAR (7)     NULL,
    [SEC-PROC-ICD10-05]     VARCHAR (7)     NULL,
    [ALLOWED-AMT]           DECIMAL (16, 3) NULL,
    [ALLOWED-SIGN]          VARCHAR (1)     NULL,
    [AMT-DEDN]              DECIMAL (16, 3) NULL,
    [AMT-DEDN-SIGN]         VARCHAR (1)     NULL,
    [SPECL-DED]             DECIMAL (16, 3) NULL,
    [SPECL-DED-SIGN]        VARCHAR (1)     NULL,
    [COINS-RATE]            DECIMAL (16, 3) NULL,
    [COINS-RATE-SIGN]       VARCHAR (1)     NULL,
    [AMT-PYMT]              DECIMAL (16, 3) NULL,
    [AMT-PYMT-SIGN]         VARCHAR (1)     NULL,
    [OTHER-CARR-AMT]        DECIMAL (16, 3) NULL,
    [OTHER-CARR-AMT-SIGN]   VARCHAR (1)     NULL,
    [AMMS-MED-ELIG-CD]      VARCHAR (4)     NULL,
    [AMMS-MED-PYMT]         DECIMAL (16, 3) NULL,
    [AMMS-MED-PYMT-SIGN]    VARCHAR (1)     NULL,
    [LINE-NO]               BIGINT          NULL,
    [COVR-INDC]             VARCHAR (4)     NULL,
    [FILLER_5]              VARCHAR (30)    NULL,
    [COB-CD]                VARCHAR (3)     NULL,
    [QUANTITY]              BIGINT          NULL,
    [QUANTITY-SIGN]         VARCHAR (1)     NULL,
    [DENT-CLASS]            VARCHAR (5)     NULL,
    [PRECERT_IND]           VARCHAR (7)     NULL,
    [CHRG_TOT]              DECIMAL (16, 3) NULL,
    [CHRG-SIGN]             VARCHAR (1)     NULL,
    [SAVINGS]               DECIMAL (16, 3) NULL,
    [SAVINGS-SIGN]          VARCHAR (1)     NULL,
    [HRA-PAID-AMT]          DECIMAL (12, 3) NULL,
    [HRA-PAID-AMT-SIGN]     VARCHAR (1)     NULL,
    [HRA-ELIG-AMT]          DECIMAL (12, 3) NULL,
    [HRA-ELIG-AMT-SIGN]     VARCHAR (1)     NULL,
    [REV_CD]                VARCHAR (4)     NULL,
    [BENE_TYP]              VARCHAR (2)     NULL,
    [ALTID]                 VARCHAR (20)    NULL,
    [FILLER_6]              VARCHAR (41)    NULL
);

