CREATE TABLE [stg].[tbl_sf_eligibility] (
    [sf_eligibility_skey]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [first_name]                       VARCHAR (100) NULL,
    [last_name]                        VARCHAR (100) NULL,
    [mailing_street]                   TEXT          NULL,
    [mailing_city]                     VARCHAR (100) NULL,
    [mailing_zip_postal_code]          VARCHAR (100) NULL,
    [mailing_state_province]           VARCHAR (100) NULL,
    [mailing_country]                  VARCHAR (100) NULL,
    [primary_phone]                    VARCHAR (100) NULL,
    [mobile_phone]                     VARCHAR (100) NULL,
    [fax]                              TEXT          NULL,
    [primary_email]                    TEXT          NULL,
    [account_name]                     TEXT          NULL,
    [eligibility_name]                 TEXT          NULL,
    [contact_record_type]              VARCHAR (100) NULL,
    [contact_id]                       TEXT          NULL,
    [home_phone]                       TEXT          NULL,
    [work_phone]                       TEXT          NULL,
    [do_not_email]                     VARCHAR (5)   NULL,
    [do_not_call]                      VARCHAR (5)   NULL,
    [birth_date]                       DATE          NULL,
    [contact_type]                     TEXT          NULL,
    [date_of_registration]             DATE          NULL,
    [ee_unique_id]                     BIGINT        NULL,
    [eligibility]                      TEXT          NULL,
    [ee_ssn]                           TEXT          NULL,
    [employee_id]                      TEXT          NULL,
    [employer_id]                      TEXT          NULL,
    [employer]                         TEXT          NULL,
    [gender]                           VARCHAR (10)  NULL,
    [home_email]                       TEXT          NULL,
    [individual_type]                  TEXT          NULL,
    [insurance_id]                     TEXT          NULL,
    [insurance_carrier]                TEXT          NULL,
    [insurance_plan]                   TEXT          NULL,
    [insurance_program]                TEXT          NULL,
    [method_of_registration]           TEXT          NULL,
    [middle_name]                      TEXT          NULL,
    [mobile_opt_out]                   TEXT          NULL,
    [referral_source]                  TEXT          NULL,
    [relationship]                     TEXT          NULL,
    [time_zone]                        ROWVERSION    NULL,
    [eligibility_custom_field_10_name] TEXT          NULL,
    [eligibility_custom_field_10]      TEXT          NULL,
    [eligibility_custom_field_1_name]  TEXT          NULL,
    [eligibility_custom_field_1]       TEXT          NULL,
    [eligibility_custom_field_2_name]  TEXT          NULL,
    [eligibility_custom_field_2]       TEXT          NULL,
    [eligibility_custom_field_3_name]  TEXT          NULL,
    [eligibility_custom_field_3]       TEXT          NULL,
    [eligibility_custom_field_4_name]  TEXT          NULL,
    [eligibility_custom_field_4]       TEXT          NULL,
    [eligibility_custom_field_5_name]  TEXT          NULL,
    [eligibility_custom_field_5]       TEXT          NULL,
    [eligibility_custom_field_6_name]  TEXT          NULL,
    [eligibility_custom_field_6]       TEXT          NULL,
    [eligibility_custom_field_7_name]  TEXT          NULL,
    [eligibility_custom_field_7]       TEXT          NULL,
    [eligibility_custom_field_8_name]  TEXT          NULL,
    [eligibility_custom_field_8]       TEXT          NULL,
    [eligibility_custom_field_9_name]  TEXT          NULL,
    [eligibility_custom_field_9]       TEXT          NULL,
    [eligibility_relationship_type]    TEXT          NULL,
    [source_file_skey]                 BIGINT        NOT NULL,
    [run_instance_skey]                BIGINT        NOT NULL,
    [stg_inserted_timestamp]           DATETIME      NOT NULL
);

