CREATE TABLE [rm].[tbl_input_LBP_RM] (
    [Member_ID]        VARCHAR (255) NOT NULL,
    [AGE_1]            BIT           NULL,
    [AGE_2]            BIT           NULL,
    [AGE_3]            BIT           NULL,
    [AGE_4]            BIT           NULL,
    [AGE_5]            BIT           NULL,
    [AGE_6]            BIT           NULL,
    [AGE_7]            BIT           NULL,
    [AGE_8]            BIT           NULL,
    [AGE_9]            BIT           NULL,
    [DX_M4316]         BIT           NULL,
    [DX_M4317]         BIT           NULL,
    [DX_M4806]         BIT           NULL,
    [DX_M48061]        BIT           NULL,
    [DX_M48062]        BIT           NULL,
    [DX_M4807]         BIT           NULL,
    [DX_M5117]         BIT           NULL,
    [DX_M961]          BIT           NULL,
    [CATSCAN]          BIT           NULL,
    [ELEC_STIMULATION] BIT           NULL,
    [THERAPY]          BIT           NULL,
    [XRAY]             BIT           NULL,
    [MRI]              BIT           NULL,
    [CHIRO]            BIT           NULL,
    [AFIB]             BIT           NULL,
    [ALZDEM]           BIT           NULL,
    [AMI]              BIT           NULL,
    [ANEMIA]           BIT           NULL,
    [ASTHMA]           BIT           NULL,
    [BPH]              BIT           NULL,
    [BREAST]           BIT           NULL,
    [CATARACT]         BIT           NULL,
    [CKD]              BIT           NULL,
    [COLORECTAL]       BIT           NULL,
    [COPD]             BIT           NULL,
    [DEPRESSION]       BIT           NULL,
    [DM1]              BIT           NULL,
    [DM2]              BIT           NULL,
    [ENDOMETRIAL]      BIT           NULL,
    [GLAUCOMA]         BIT           NULL,
    [HF]               BIT           NULL,
    [HIPFRAC]          BIT           NULL,
    [HTN]              BIT           NULL,
    [HYPLIP]           BIT           NULL,
    [HYPOTHYROIDISM]   BIT           NULL,
    [IHD]              BIT           NULL,
    [LUNG]             BIT           NULL,
    [OST]              BIT           NULL,
    [PROSTATE]         BIT           NULL,
    [RAOA]             BIT           NULL,
    [STROKE]           BIT           NULL,
    [FEMALE]           BIT           NULL,
    [SURGERY]          BIT           NULL,
    [Seq_ID]           INT           IDENTITY (1, 1) NOT NULL,
    [Rec_Insert_Dt]    DATETIME      DEFAULT (getdate()) NOT NULL,
    [Rec_Update_Dt]    DATETIME      DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([Member_ID] ASC)
);

